Advanced NumPy

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

ndarray Object Internals

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

NumPy dtype Hierarchy

In [5]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [6]:
np.issubdtype(floats.dtype, np.floating)

True

In [7]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [8]:
np.issubdtype(ints.dtype, np.number)

True

Advanced Array Manipulation

Reshaping Arrays

In [12]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
other_arr = np.ones((3, 5))

In [17]:
other_arr.shape

(3, 5)

In [18]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

C Versus Fortran Order

In [22]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

Concatenating and Splitting Arrays

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
arr = np.random.randn(5, 2)
arr

array([[-0.2047,  0.4789],
       [-0.5194, -0.5557],
       [ 1.9658,  1.3934],
       [ 0.0929,  0.2817],
       [ 0.769 ,  1.2464]])

In [30]:
first, second, third = np.split(arr, [1, 3])

In [31]:
first

array([[-0.2047,  0.4789]])

In [32]:
second

array([[-0.5194, -0.5557],
       [ 1.9658,  1.3934]])

In [33]:
third

array([[0.0929, 0.2817],
       [0.769 , 1.2464]])

Stacking helpers: r and c

In [34]:
arr = np.arange(6)

In [35]:
arr1 = arr.reshape((3, 2))

In [36]:
arr2 = np.random.randn(3, 2)

In [37]:
np.r_[arr1, arr2]

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [ 1.0072, -1.2962],
       [ 0.275 ,  0.2289],
       [ 1.3529,  0.8864]])

In [38]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [ 1.0072, -1.2962,  3.    ],
       [ 0.275 ,  0.2289,  4.    ],
       [ 1.3529,  0.8864,  5.    ]])

In [39]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

Repeating Elements: tile and repeat

In [40]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [41]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [42]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [43]:
arr = np.random.randn(2, 2)
arr

array([[-2.0016, -0.3718],
       [ 1.669 , -0.4386]])

In [44]:
arr.repeat(2, axis=0)

array([[-2.0016, -0.3718],
       [-2.0016, -0.3718],
       [ 1.669 , -0.4386],
       [ 1.669 , -0.4386]])

In [45]:
arr.repeat([2, 3], axis=0)

array([[-2.0016, -0.3718],
       [-2.0016, -0.3718],
       [ 1.669 , -0.4386],
       [ 1.669 , -0.4386],
       [ 1.669 , -0.4386]])

In [46]:
arr.repeat([2, 3], axis=1)

array([[-2.0016, -2.0016, -0.3718, -0.3718, -0.3718],
       [ 1.669 ,  1.669 , -0.4386, -0.4386, -0.4386]])

In [47]:
arr

array([[-2.0016, -0.3718],
       [ 1.669 , -0.4386]])

In [48]:
np.tile(arr, 2)

array([[-2.0016, -0.3718, -2.0016, -0.3718],
       [ 1.669 , -0.4386,  1.669 , -0.4386]])

In [49]:
arr

array([[-2.0016, -0.3718],
       [ 1.669 , -0.4386]])

In [50]:
np.tile(arr, (2, 1))

array([[-2.0016, -0.3718],
       [ 1.669 , -0.4386],
       [-2.0016, -0.3718],
       [ 1.669 , -0.4386]])

In [51]:
np.tile(arr, (3, 2))

array([[-2.0016, -0.3718, -2.0016, -0.3718],
       [ 1.669 , -0.4386,  1.669 , -0.4386],
       [-2.0016, -0.3718, -2.0016, -0.3718],
       [ 1.669 , -0.4386,  1.669 , -0.4386],
       [-2.0016, -0.3718, -2.0016, -0.3718],
       [ 1.669 , -0.4386,  1.669 , -0.4386]])

Fancy Indexing Equivalents: take and put

In [52]:
arr = np.arange(10) * 100

In [53]:
inds = [7, 1, 2, 6]

In [54]:
arr[inds]

array([700, 100, 200, 600])

In [55]:
arr.take(inds)

array([700, 100, 200, 600])

In [56]:
arr.put(inds, 42)

In [57]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [58]:
arr.put(inds, [40, 41, 42, 43])

In [59]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [60]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[-0.5397,  0.477 ,  3.2489, -1.0212],
       [-0.5771,  0.1241,  0.3026,  0.5238]])

In [61]:
arr.take(inds, axis=1)

array([[ 3.2489, -0.5397,  3.2489,  0.477 ],
       [ 0.3026, -0.5771,  0.3026,  0.1241]])

Broadcasting 

In [62]:
arr = np.arange(5)

In [63]:
arr

array([0, 1, 2, 3, 4])

In [64]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [65]:
arr = np.random.randn(4, 3)
arr.mean(0)

array([-0.3928, -0.3824, -0.8768])

In [66]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 0.3937,  1.7263,  0.1633],
       [-0.4384, -1.9878, -0.9839],
       [-0.468 ,  0.9426, -0.3891],
       [ 0.5126, -0.6811,  1.2097]])

In [67]:
demeaned.mean(0)

array([-0.,  0., -0.])

In [68]:
arr

array([[ 0.0009,  1.3438, -0.7135],
       [-0.8312, -2.3702, -1.8608],
       [-0.8608,  0.5601, -1.2659],
       [ 0.1198, -1.0635,  0.3329]])

In [69]:
row_means = arr.mean(1)

In [70]:
row_means.shape

(4,)

In [71]:
row_means.reshape((4, 1))

array([[ 0.2104],
       [-1.6874],
       [-0.5222],
       [-0.2036]])

In [72]:
demeaned = arr - row_means.reshape((4, 1))

In [73]:
demeaned.mean(1)

array([ 0., -0.,  0.,  0.])

Broadcasting Over Other Axes

In [75]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.2095,  1.1334, -0.9239],
       [ 0.8562, -0.6828, -0.1734],
       [-0.3386,  1.0823, -0.7438],
       [ 0.3234, -0.8599,  0.5365]])

In [76]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [77]:
arr_1d = np.random.normal(size=3)
arr_1d[:, np.newaxis]

array([[-2.3594],
       [-0.1995],
       [-1.542 ]])

In [78]:
arr_1d[np.newaxis, :]

array([[-2.3594, -0.1995, -1.542 ]])

In [79]:
arr = np.random.randn(3, 4, 5)
depth_means = arr.mean(2)
depth_means

array([[-0.4735,  0.3971, -0.0228,  0.2001],
       [-0.3521, -0.281 , -0.071 , -0.1586],
       [ 0.6245,  0.6047,  0.4396, -0.2846]])

In [80]:
depth_means.shape

(3, 4)

In [81]:
demeaned = arr - depth_means[:, :, np.newaxis]

In [82]:
demeaned.mean(2)

array([[ 0.,  0., -0., -0.],
       [ 0.,  0., -0.,  0.],
       [ 0.,  0., -0., -0.]])

Setting Array Values by Broadcasting

In [83]:
arr = np.zeros((4, 3))

In [84]:
arr[:] = 5

In [85]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [86]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [87]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

Advanced ufunc Usage

ufunc Instance Methods

In [88]:
arr = np.arange(10)

In [89]:
np.add.reduce(arr)

45

In [90]:
arr.sum()

45

In [91]:
np.random.seed(12346)  # for reproducibility
arr = np.random.randn(5, 5)
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [92]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [93]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [94]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [95]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [96]:
x, y = np.random.randn(3, 4), np.random.randn(5)

In [97]:
result = np.subtract.outer(x, y)

In [98]:
result.shape

(3, 4, 5)

In [99]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17], dtype=int32)

In [100]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [101]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

Writing New ufuncs in Python

In [102]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [103]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [104]:
arr = np.random.randn(10000)

In [105]:
%timeit add_them(arr, arr)

3.96 ms ± 679 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [106]:
%timeit np.add(arr, arr)

9.09 µs ± 534 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Structured and Record Arrays

In [107]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5   ,  6), (3.1416, -2)], dtype=[('x', '<f8'), ('y', '<i4')])

In [108]:
sarr[0]

(1.5, 6)

In [109]:
sarr[0]['y']

6

In [110]:
sarr['x']


array([1.5   , 3.1416])

Nested dtypes and Multidimensional Fields


In [111]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [112]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [113]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [114]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)


array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [117]:
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [115]:
data['y']

array([5, 6])

In [116]:
data['x']['a']

array([1., 3.])

Why Use Structured Arrays?


More About Sorting

In [118]:
arr = np.random.randn(6)
arr.sort()
arr

array([-1.082 ,  0.3759,  0.8014,  1.1397,  1.2888,  1.8413])

In [119]:
arr = np.random.randn(3, 5)
arr

array([[-0.3318, -1.4711,  0.8705, -0.0847, -1.1329],
       [-1.0111, -0.3436,  2.1714,  0.1234, -0.0189],
       [ 0.1773,  0.7424,  0.8548,  1.038 , -0.329 ]])

In [120]:
arr[:, 0].sort()  # Sort first column values in-place
arr

array([[-1.0111, -1.4711,  0.8705, -0.0847, -1.1329],
       [-0.3318, -0.3436,  2.1714,  0.1234, -0.0189],
       [ 0.1773,  0.7424,  0.8548,  1.038 , -0.329 ]])

In [121]:
arr = np.random.randn(5)
arr

array([-1.1181, -0.2415, -2.0051,  0.7379, -1.0614])

In [122]:
np.sort(arr)
arr

array([-1.1181, -0.2415, -2.0051,  0.7379, -1.0614])

In [123]:
arr = np.random.randn(3, 5)
arr

array([[ 0.5955, -0.2682,  1.3389, -0.1872,  0.9111],
       [-0.3215,  1.0054, -0.5168,  1.1925, -0.1989],
       [ 0.3969, -1.7638,  0.6071, -0.2222, -0.2171]])

In [124]:
arr.sort(axis=1)
arr

array([[-0.2682, -0.1872,  0.5955,  0.9111,  1.3389],
       [-0.5168, -0.3215, -0.1989,  1.0054,  1.1925],
       [-1.7638, -0.2222, -0.2171,  0.3969,  0.6071]])

In [125]:
arr[:, ::-1]

array([[ 1.3389,  0.9111,  0.5955, -0.1872, -0.2682],
       [ 1.1925,  1.0054, -0.1989, -0.3215, -0.5168],
       [ 0.6071,  0.3969, -0.2171, -0.2222, -1.7638]])

Indirect Sorts: argsort and lexsort


In [126]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [127]:
values[indexer]

array([0, 1, 2, 3, 5])

In [128]:
arr = np.random.randn(3, 5)
arr[0] = values
arr

array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [-0.3636, -0.1378,  2.1777, -0.4728,  0.8356],
       [-0.2089,  0.2316,  0.728 , -1.3918,  1.9956]])

In [129]:
arr[:, arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [-0.1378,  2.1777,  0.8356, -0.4728, -0.3636],
       [ 0.2316,  0.728 ,  1.9956, -1.3918, -0.2089]])

In [130]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [131]:
zip(last_name[sorter], first_name[sorter])

Alternative Sort Algorithms


In [132]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
                   '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [133]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

Partially Sorting Arrays


In [134]:
np.random.seed(12345)
arr = np.random.randn(20)
arr

array([-0.2047,  0.4789, -0.5194, -0.5557,  1.9658,  1.3934,  0.0929,
        0.2817,  0.769 ,  1.2464,  1.0072, -1.2962,  0.275 ,  0.2289,
        1.3529,  0.8864, -2.0016, -0.3718,  1.669 , -0.4386])

In [135]:
np.partition(arr, 3)

array([-2.0016, -1.2962, -0.5557, -0.5194, -0.3718, -0.4386, -0.2047,
        0.2817,  0.769 ,  0.4789,  1.0072,  0.0929,  0.275 ,  0.2289,
        1.3529,  0.8864,  1.3934,  1.9658,  1.669 ,  1.2464])

In [136]:
indices = np.argpartition(arr, 3)
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9], dtype=int64)

In [137]:
arr.take(indices)

array([-2.0016, -1.2962, -0.5557, -0.5194, -0.3718, -0.4386, -0.2047,
        0.2817,  0.769 ,  0.4789,  1.0072,  0.0929,  0.275 ,  0.2289,
        1.3529,  0.8864,  1.3934,  1.9658,  1.669 ,  1.2464])

numpy.searchsorted: Finding Elements in a Sorted Array


In [138]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [139]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5], dtype=int64)

In [140]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])

In [141]:
arr.searchsorted([0, 1])

array([0, 3], dtype=int64)

In [142]:
arr.searchsorted([0, 1], side='right')

array([3, 7], dtype=int64)

In [143]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([9940., 6768., 7908., 1709.,  268., 8003., 9037.,  246., 4917.,
       5262., 5963.,  519., 8950., 7282., 8183., 5002., 8101.,  959.,
       2189., 2587., 4681., 4593., 7095., 1780., 5314., 1677., 7688.,
       9281., 6094., 1501., 4896., 3773., 8486., 9110., 3838., 3154.,
       5683., 1878., 1258., 6875., 7996., 5735., 9732., 6340., 8884.,
       4954., 3516., 7142., 5039., 2256.])

In [144]:
labels = bins.searchsorted(data)
labels

array([4, 4, 4, 3, 2, 4, 4, 2, 3, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 3, 3, 3,
       4, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 4, 4, 3], dtype=int64)

In [145]:
pd.Series(data).groupby(labels).mean()

2     498.000000
3    3064.277778
4    7389.035714
dtype: float64

A.7 Writing Fast NumPy Functions with Numba

In [3]:
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [4]:
x = np.random.randn(10000000)
y = np.random.randn(10000000)

In [5]:
%timeit mean_distance(x, y)

6.79 s ± 372 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit (x - y).mean()

69.3 ms ± 2.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
import numba as nb
numba_mean_distance = nb.jit(mean_distance)

In [8]:
@nb.jit
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [9]:
%timeit numba_mean_distance(x, y)

15.7 ms ± 356 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
from numba import float64, njit

@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()

Creating Custom numpy.ufunc Objects with Numba


In [11]:
from numba import vectorize

@vectorize
def nb_add(x, y):
    return x + y

In [31]:
x = np.arange(10)
nb_add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

In [40]:
#nb_add.accumulate(x, 0)
np.frompyfunc(lambda x,y:x+y,2,1).accumulate(np.arange(10,dtype=object))

array([0, 1, 3, 6, 10, 15, 21, 28, 36, 45], dtype=object)

A.8 Advanced Array Input and Output


Memory-Mapped Files

In [42]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+',
                 shape=(10000, 10000))
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [43]:
section = mmap[:5]

In [44]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap

memmap([[-1.9681,  0.8854,  0.0447, ...,  1.3495, -1.4499, -0.7174],
        [ 0.6962, -1.503 ,  1.6012, ..., -0.9228, -0.4397, -1.1563],
        [ 0.297 ,  0.8569, -0.443 , ...,  1.437 ,  0.8725, -0.8138],
        ...,
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [45]:
del mmap

In [46]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

memmap([[-1.9681,  0.8854,  0.0447, ...,  1.3495, -1.4499, -0.7174],
        [ 0.6962, -1.503 ,  1.6012, ..., -0.9228, -0.4397, -1.1563],
        [ 0.297 ,  0.8569, -0.443 , ...,  1.437 ,  0.8725, -0.8138],
        ...,
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

HDF5 and Other Array Storage Options


Performance Tips


The Importance of Contiguous Memory

In [49]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [50]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [51]:
arr_f.flags.f_contiguous

True

In [52]:
%timeit arr_c.sum(1)

957 µs ± 35.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [53]:
%timeit arr_f.sum(1)

623 µs ± 41.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [55]:
arr_c[:50].flags.contiguous

True

In [56]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [57]:
%xdel arr_c
%xdel arr_f

In [58]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

In [2]:
 %run first/second/third/data_script.py

ERROR:root:File `'first/second/third/data_script.py'` not found.


In [4]:
foo = %pwd

In [7]:
foo

'C:\\Users\\IlknurKaraduman'

In [8]:
2 ** 27

134217728

In [9]:
_

134217728

In [10]:
__

134217728

In [11]:
foo = 'bar'
foo

'bar'

In [12]:
_i11

"foo = 'bar'\nfoo"

In [13]:
_11

'bar'

In [14]:
exec(_i11)

In [15]:
ip_info = !ifconfig wlan0 | grep "inet "
ip_info[0].strip()

"'ifconfig' is not recognized as an internal or external command,"

In [ ]:
foo = 'exam*'
!cmd $foo

In [ ]:
alias ll ls -l
ll /usr

In [ ]:
%alias test_alias (cd examples; ls; cd ..)
test_alias

ek b

In [2]:
%bookmark py4da /Desktop/examples

In [3]:
cd py4da

(bookmark:py4da) -> /Desktop/examples
[WinError 3] Sistem belirtilen yolu bulamıyor: '/Desktop/examples'
C:\Users\IlknurKaraduman


In [4]:
%bookmark -l

Current bookmarks:
py4da -> /Desktop/examples


In [6]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.


In [8]:
# a very large list of strings
strings = ['foo', 'foobar', 'baz', 'qux',
 'python', 'Guido Van Rossum'] * 100000
method1 = [x for x in strings if x.startswith('foo')]
method2 = [x for x in strings if x[:3] == 'foo']

In [9]:
%time method1 = [x for x in strings if x.startswith('foo')]

Wall time: 177 ms


In [10]:
%time method2 = [x for x in strings if x[:3] == 'foo']

Wall time: 142 ms


In [11]:
%timeit [x for x in strings if x.startswith('foo')]

195 ms ± 16.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit [x for x in strings if x[:3] == 'foo']

124 ms ± 7.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
x = 'foobar'
y = 'foo'

In [14]:
%timeit x.startswith(y)

389 ns ± 28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit x[:3] == y

300 ns ± 48.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
from numpy.random import randn
def add_and_sum(x, y):
    added = x + y
    summed = added.sum(axis=1)
    return summed
def call_function():
    x = randn(1000, 1000)
    y = randn(1000, 1000)
    return add_and_sum(x, y)

In [21]:
x = randn(3000, 3000)
y = randn(3000, 3000)
%prun add_and_sum(x, y)

         7 function calls in 0.102 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.068    0.068    0.088    0.088 <ipython-input-17-0355268a1452>:2(add_and_sum)
        1    0.020    0.020    0.020    0.020 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.013    0.013    0.102    0.102 <string>:1(<module>)
        1    0.000    0.000    0.102    0.102 {built-in method builtins.exec}
        1    0.000    0.000    0.020    0.020 {method 'sum' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.020    0.020 _methods.py:36(_sum)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

In [ ]:
import some_lib
import importlib
importlib.reload(some_lib)